// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMcbSzNYfaYehlnVdF-mPYY5NTn0dXW9Y',
    appId: '1:1046057211156:web:511f87bea8de74f7465e01',
    messagingSenderId: '1046057211156',
    projectId: 'demonotification-a16c9',
    authDomain: 'demonotification-a16c9.firebaseapp.com',
    storageBucket: 'demonotification-a16c9.appspot.com',
    measurementId: 'G-HS4JGK8XM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGuGiSYusGqpIWmzYvLag5xA0ipHPk_Io',
    appId: '1:1046057211156:android:5dd3e82498b05e0e465e01',
    messagingSenderId: '1046057211156',
    projectId: 'demonotification-a16c9',
    storageBucket: 'demonotification-a16c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFDQTRd0C-ws8iGomC53-AJSsy8gfl_0',
    appId: '1:1046057211156:ios:38997cb122bc4072465e01',
    messagingSenderId: '1046057211156',
    projectId: 'demonotification-a16c9',
    storageBucket: 'demonotification-a16c9.appspot.com',
    iosBundleId: 'com.example.fcmDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOFDQTRd0C-ws8iGomC53-AJSsy8gfl_0',
    appId: '1:1046057211156:ios:38997cb122bc4072465e01',
    messagingSenderId: '1046057211156',
    projectId: 'demonotification-a16c9',
    storageBucket: 'demonotification-a16c9.appspot.com',
    iosBundleId: 'com.example.fcmDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMcbSzNYfaYehlnVdF-mPYY5NTn0dXW9Y',
    appId: '1:1046057211156:web:028bb86c368c21d5465e01',
    messagingSenderId: '1046057211156',
    projectId: 'demonotification-a16c9',
    authDomain: 'demonotification-a16c9.firebaseapp.com',
    storageBucket: 'demonotification-a16c9.appspot.com',
    measurementId: 'G-DK4Y1B2MWQ',
  );
}
